load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Counter",
    srcs = glob(["*.swift"]),
    module_name = "Counter",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//Core/StringUtils",
        "//Core/UIComponents:UIComponentsLib",
    ],
)
